# Generated by Django 4.2.1 on 2023-05-29 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('fecha', models.DateTimeField(auto_created=True)),
                ('id_venta', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
                ('bruto', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
