# Generated by Django 4.2.1 on 2023-06-05 00:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_venta_fecha_alter_venta_id_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='id_venta',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='bruto',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='estado',
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 20, 31, 53, 488253)),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
        ),
    ]
