# Generated by Django 4.2.1 on 2023-06-19 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_id_venta_venta_id_rename_bruto_venta_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 14, 18, 42, 900855)),
        ),
    ]
